kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  name: tekton-clustertriggerbindings-view-role
rules:
  - apiGroups:
      - triggers.tekton.dev
    resources:
      - clustertriggerbindings
    verbs:
      - get
      - list
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-clustertriggerbindings-view-rolebinding-all-users
roleRef:
  kind: ClusterRole
  name: tekton-clustertriggerbindings-view-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:authenticated
