export TEKTON_PIPELINE_VERSION=latest
export TEKTON_TRIGGERS_VERSION=latest
export TEKTON_RESULTS_VERSION=v0.4.0
export TEKTON_DASHBOARD_VERSION=latest
export TEKTON_CHAINS_VERSION=latest
export PAC_VERSION=stable
export TEKTON_HUB_VERSION=v1.7.2
