export TEKTON_PIPELINE_VERSION=v0.33.2
export TEKTON_TRIGGERS_VERSION=v0.19.0
export TEKTON_RESULTS_VERSION=v0.4.0
export TEKTON_DASHBOARD_VERSION=v0.24.1
export TEKTON_CHAINS_VERSION=v0.8.0
export TEKTON_HUB_VERSION=v1.7.1
export PAC_VERSION=0.5.6
