# Copyright 2020 The Tekton Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
namespace: tekton-operator

patches:
- path: operator.yaml
  target:
    kind: Deployment
    name: tekton-operator
- path: webhook.yaml
  target:
    kind: Deployment
    name: tekton-operator-webhook

configMapGenerator:
- name: tekton-config-defaults
  literals:
  - DEFAULT_TARGET_NAMESPACE=tekton-pipelines
  behavior: merge
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base/
- 300-operator_v1alpha1_dashboard_crd.yaml
- 300-operator_v1alpha1_result_crd.yaml
- service_account.yaml
- operator_service.yaml
