/*
Copyright 2020 The Tekton Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ManualApprovalGateListerExpansion allows custom methods to be added to
// ManualApprovalGateLister.
type ManualApprovalGateListerExpansion interface{}

// OpenShiftPipelinesAsCodeListerExpansion allows custom methods to be added to
// OpenShiftPipelinesAsCodeLister.
type OpenShiftPipelinesAsCodeListerExpansion interface{}

// TektonAddonListerExpansion allows custom methods to be added to
// TektonAddonLister.
type TektonAddonListerExpansion interface{}

// TektonChainListerExpansion allows custom methods to be added to
// TektonChainLister.
type TektonChainListerExpansion interface{}

// TektonConfigListerExpansion allows custom methods to be added to
// TektonConfigLister.
type TektonConfigListerExpansion interface{}

// TektonDashboardListerExpansion allows custom methods to be added to
// TektonDashboardLister.
type TektonDashboardListerExpansion interface{}

// TektonHubListerExpansion allows custom methods to be added to
// TektonHubLister.
type TektonHubListerExpansion interface{}

// TektonInstallerSetListerExpansion allows custom methods to be added to
// TektonInstallerSetLister.
type TektonInstallerSetListerExpansion interface{}

// TektonPipelineListerExpansion allows custom methods to be added to
// TektonPipelineLister.
type TektonPipelineListerExpansion interface{}

// TektonPrunerListerExpansion allows custom methods to be added to
// TektonPrunerLister.
type TektonPrunerListerExpansion interface{}

// TektonResultListerExpansion allows custom methods to be added to
// TektonResultLister.
type TektonResultListerExpansion interface{}

// TektonSchedulerListerExpansion allows custom methods to be added to
// TektonSchedulerLister.
type TektonSchedulerListerExpansion interface{}

// TektonTriggerListerExpansion allows custom methods to be added to
// TektonTriggerLister.
type TektonTriggerListerExpansion interface{}
