/*
Copyright 2020 The Tekton Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	operatorv1alpha1 "github.com/tektoncd/operator/pkg/apis/operator/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// TektonAddonLister helps list TektonAddons.
// All objects returned here must be treated as read-only.
type TektonAddonLister interface {
	// List lists all TektonAddons in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*operatorv1alpha1.TektonAddon, err error)
	// Get retrieves the TektonAddon from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*operatorv1alpha1.TektonAddon, error)
	TektonAddonListerExpansion
}

// tektonAddonLister implements the TektonAddonLister interface.
type tektonAddonLister struct {
	listers.ResourceIndexer[*operatorv1alpha1.TektonAddon]
}

// NewTektonAddonLister returns a new TektonAddonLister.
func NewTektonAddonLister(indexer cache.Indexer) TektonAddonLister {
	return &tektonAddonLister{listers.New[*operatorv1alpha1.TektonAddon](indexer, operatorv1alpha1.Resource("tektonaddon"))}
}
