/*
Copyright 2020 The Tekton Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	operatorv1alpha1 "github.com/tektoncd/operator/pkg/apis/operator/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// TektonDashboardLister helps list TektonDashboards.
// All objects returned here must be treated as read-only.
type TektonDashboardLister interface {
	// List lists all TektonDashboards in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*operatorv1alpha1.TektonDashboard, err error)
	// Get retrieves the TektonDashboard from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*operatorv1alpha1.TektonDashboard, error)
	TektonDashboardListerExpansion
}

// tektonDashboardLister implements the TektonDashboardLister interface.
type tektonDashboardLister struct {
	listers.ResourceIndexer[*operatorv1alpha1.TektonDashboard]
}

// NewTektonDashboardLister returns a new TektonDashboardLister.
func NewTektonDashboardLister(indexer cache.Indexer) TektonDashboardLister {
	return &tektonDashboardLister{listers.New[*operatorv1alpha1.TektonDashboard](indexer, operatorv1alpha1.Resource("tektondashboard"))}
}
