# Copyright 2023 The Tekton Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tekton-resource-pruner
  labels:
    app.kubernetes.io/part-of: tekton-config
rules:
  # allow tkn command to delete pipelinerun and taskrun
  - apiGroups:
      - tekton.dev
    resources:
      - taskruns
      - pipelineruns
    verbs:
      - list
      - get
      - delete
      - deletecollection
  # allow tkn command to list pipelines and tasks
  # if individual resource selection enabled,
  # tkn cmd has to get pipelinerun and taskrun parent resource names
  # ie, pipelines, tasks
  - apiGroups:
      - tekton.dev
    resources:
      - tasks
      - pipelines
    verbs:
      - list

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-resource-pruner
  namespace: tekton-pipelines
  labels:
    app.kubernetes.io/part-of: tekton-config

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-resource-pruner
  labels:
    app.kubernetes.io/part-of: tekton-config
subjects:
  - kind: ServiceAccount
    name: tekton-resource-pruner
    namespace: tekton-pipelines
roleRef:
  kind: ClusterRole
  name: tekton-resource-pruner
  apiGroup: rbac.authorization.k8s.io
