version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    labels:
    - "ok-to-test"
    - "dependencies"
    - "kind/misc"
    - "release-note-none"
    ignore:
    - dependency-name: "k8s.io/*"
      update-types: ["version-update:semver-major", "version-update:semver-minor"]
    - dependency-name: "github.com/openshift/client-go"
