# Documentation: https://golangci-lint.run/usage/configuration/

linters-settings:
  gosec:
    excludes:
      - G601
    exclude-generated: true
  errcheck:
    exclude-functions:
      - (*github.com/tektoncd/pipeline/vendor/go.uber.org/zap.SugaredLogger).Sync
      - flag.Set
      - os.Setenv
      - logger.Sync
      - fmt.Fprintf
      - fmt.Fprintln
      - (io.Closer).Close
      - updateConfigMap
  gomodguard:
    blocked:
      modules:
        - github.com/ghodss/yaml:
            recommendations:
              - sigs.k8s.io/yaml
  depguard:
    rules:
      prevent_unmaintained_packages:
        list-mode: lax # allow unless explicitely denied
        files:
          - $all
          - "!$test"
        allow:
          - $gostd
        deny:
          - pkg: io/ioutil
            desc: "replaced by io and os packages since Go 1.16: https://tip.golang.org/doc/go1.16#ioutil"
          - pkg: github.com/ghodss/yaml
            desc: "use sigs.k8s.io/yaml instead, to be consistent"
linters:
  disable-all: true
  enable:
  - unused
  - errcheck
  - gofmt
  - goimports
  - gomodguard
  - unconvert
issues:
  uniq-by-line: false
  # Note: path identifiers are regular expressions, hence the \.go suffixes.
  exclude-rules:
  - path: main\.go
    linters:
    - forbidigo
  - path: _test\.go
    linters:
    - dogsled
    - errcheck
    - goconst
    - gosec
    - ineffassign
    - maintidx
    - typecheck
  max-issues-per-linter: 0
  max-same-issues: 0
  include:
  # Enable off-by-default rules for revive requiring that all exported elements have a properly formatted comment.
  - EXC0012 # https://golangci-lint.run/usage/false-positives/#exc0012
  - EXC0014 # https://golangci-lint.run/usage/false-positives/#exc0014
  exclude-files:
  - .*/zz_generated.deepcopy.go
  - pkg/apis/pipeline/v1beta1/openapi_generated.go
  exclude-dirs:
  - vendor
  - pkg/client
  - pkg/spire/test
run:
  issues-exit-code: 1
  build-tags:
  - e2e
  timeout: 20m
  modules-download-mode: vendor


