defaultBaseImage: gcr.io/distroless/static:nonroot
baseImageOverrides:
  github.com/tektoncd/operator/cmd/openshift/operator: registry.access.redhat.com/ubi8/ubi-minimal
  github.com/tektoncd/operator/cmd/openshift/webhook: registry.access.redhat.com/ubi8/ubi-minimal
  github.com/tektoncd/operator/cmd/openshift/proxy-webhook: registry.access.redhat.com/ubi8/ubi-minimal
  github.com/tektoncd/operator/cmd/kubernetes/webhook: build-harbor.alauda.cn/ops/alpine:3
