defaultBaseImage: ghcr.io/distroless/static
baseImageOverrides:
  github.com/tektoncd/operator/cmd/openshift/operator: registry.access.redhat.com/ubi8/ubi-minimal
  github.com/tektoncd/operator/cmd/openshift/webhook: registry.access.redhat.com/ubi8/ubi-minimal
  github.com/tektoncd/operator/cmd/openshift/proxy-webhook: registry.access.redhat.com/ubi8/ubi-minimal
