chains:
  github: tektoncd/chains
  version: v0.17.1
dashboard:
  github: tektoncd/dashboard
  version: v0.39.0
hub:
  github: tektoncd/hub
  version: v1.14.2
pipeline:
  github: tektoncd/pipeline
  version: v0.50.4
pipelines-as-code:
  github: openshift-pipelines/pipelines-as-code
  version: v0.21.5
results:
  github: tektoncd/results
  version: v0.8.1
triggers:
  github: tektoncd/triggers
  version: v0.25.2
