chains:
  github: tektoncd/chains
  version: v0.15.0
dashboard:
  github: tektoncd/dashboard
  version: v0.34.0
hub:
  github: tektoncd/hub
  version: v1.12.1
pipeline:
  github: tektoncd/pipeline
  version: v0.46.0
pipelines-as-code:
  github: openshift-pipelines/pipelines-as-code
  version: v0.17.2
results:
  github: tektoncd/results
  version: v0.5.0
triggers:
  github: tektoncd/triggers
  version: v0.23.1
