{{- if .Values.rbac.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tekton-operator.serviceAccountName" . }}
  labels:
    {{- include "tekton-operator.labels" . | nindent 4 }}
  {{- with .Values.rbac.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "tekton-operator.fullname" . }}
  labels:
    {{- include "tekton-operator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - pods
    verbs:
      - get
      - list
      - watch

{{- if .Values.openshift.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tekton-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  - pods/log
  - limitranges
  verbs:
  - delete
  - deletecollection
  - create
  - patch
  - get
  - list
  - update
  - watch
- apiGroups:
  - extensions
  - apps
  resources:
  - ingresses
  - ingresses/status
  verbs:
  - delete
  - create
  - patch
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  - deployments/finalizers
  verbs:
  - delete
  - deletecollection
  - create
  - patch
  - get
  - list
  - update
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
  - delete
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - roles
  verbs:
  - delete
  - deletecollection
  - create
  - patch
  - get
  - list
  - update
  - watch
  - bind
  - escalate
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch
  - impersonate
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - rolebindings
  verbs:
  - get
  - create
  - update
  - delete
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  - customresourcedefinitions/status
  verbs:
  - get
  - create
  - update
  - delete
  - list
  - patch
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch
- apiGroups:
  - build.knative.dev
  resources:
  - builds
  - buildtemplates
  - clusterbuildtemplates
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch
- apiGroups:
  - extensions
  resources:
  - deployments
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch
- apiGroups:
  - extensions
  resources:
  - deployments/finalizers
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  verbs:
  - get
  - create
  - update
  - delete
  - use
- apiGroups:
  - operator.tekton.dev
  resources:
  - '*'
  - tektonaddons
  verbs:
  - delete
  - deletecollection
  - create
  - patch
  - get
  - list
  - update
  - watch
- apiGroups:
  - tekton.dev
  - triggers.tekton.dev
  - operator.tekton.dev
  resources:
  - '*'
  verbs:
  - add
  - delete
  - deletecollection
  - create
  - patch
  - get
  - list
  - update
  - watch
- apiGroups:
  - dashboard.tekton.dev
  resources:
  - '*'
  - tektonaddons
  verbs:
  - delete
  - deletecollection
  - create
  - patch
  - get
  - list
  - update
  - watch
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - use
  - get
  - create
  - update
  - delete
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - get
  - list
  - create
  - update
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch
- apiGroups:
  - console.openshift.io
  resources:
  - consoleyamlsamples
  - consoleclidownloads
  - consolequickstarts
  verbs:
  - delete
  - deletecollection
  - create
  - patch
  - get
  - list
  - update
  - watch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - delete
  - create
  - patch
  - get
  - list
  - update
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - delete
  - deletecollection
  - create
  - patch
  - get
  - list
  - update
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - delete
  - deletecollection
  - create
  - patch
  - get
  - list
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  verbs:
  - delete
  - deletecollection
  - create
  - patch
  - get
  - list
  - update
  - watch
  # finalizers are needed for the owner reference of the webhook
- apiGroups:
  - ""
  resources:
  - "namespaces/finalizers"
  verbs:
  - "update"
- apiGroups:
  - resolution.tekton.dev
  resources:
  - resolutionrequests
  verbs:
  - get
  - list
  - watch
  - create
  - delete
{{- else }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "tekton-operator.fullname" . }}
  labels:
    {{- include "tekton-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
    - ""
  resources:
    - pods
    - services
    - endpoints
    - persistentvolumeclaims
    - events
    - configmaps
    - secrets
    - pods/log
    - limitranges
  verbs:
    - delete
    - deletecollection
    - create
    - patch
    - get
    - list
    - update
    - watch
- apiGroups:
    - extensions
    - apps
  resources:
    - ingresses
    - ingresses/status
  verbs:
    - delete
    - create
    - patch
    - get
    - list
    - update
    - watch
- apiGroups:
    - ""
  resources:
    - namespaces
  verbs:
    - get
    - list
    - create
    - update
    - delete
    - patch
    - watch
- apiGroups:
    - ""
  resources:
    - namespaces/finalizers
  verbs:
    - update
- apiGroups:
    - apps
  resources:
    - deployments
    - daemonsets
    - replicasets
    - statefulsets
    - deployments/finalizers
  verbs:
    - get
    - list
    - create
    - update
    - delete
    - deletecollection
    - patch
    - watch
- apiGroups:
    - monitoring.coreos.com
  resources:
    - servicemonitors
  verbs:
    - get
    - create
    - delete
- apiGroups:
    - rbac.authorization.k8s.io
  resources:
    - clusterroles
    - roles
  verbs:
    - get
    - create
    - update
    - delete
- apiGroups:
    - ""
  resources:
    - serviceaccounts
  verbs:
    - get
    - list
    - create
    - update
    - delete
    - patch
    - watch
    - impersonate
- apiGroups:
    - rbac.authorization.k8s.io
  resources:
    - clusterrolebindings
    - rolebindings
  verbs:
    - get
    - create
    - update
    - delete
- apiGroups:
    - apiextensions.k8s.io
  resources:
    - customresourcedefinitions
    - customresourcedefinitions/status
  verbs:
    - get
    - create
    - update
    - delete
    - list
    - patch
    - watch
- apiGroups:
    - admissionregistration.k8s.io
  resources:
    - mutatingwebhookconfigurations
    - validatingwebhookconfigurations
  verbs:
    - get
    - list
    - create
    - update
    - delete
    - patch
    - watch
- apiGroups:
    - build.knative.dev
  resources:
    - builds
    - buildtemplates
    - clusterbuildtemplates
  verbs:
    - get
    - list
    - create
    - update
    - delete
    - patch
    - watch
- apiGroups:
    - extensions
  resources:
    - deployments
  verbs:
    - get
    - list
    - create
    - update
    - delete
    - patch
    - watch
- apiGroups:
    - extensions
  resources:
    - deployments/finalizers
  verbs:
    - get
    - list
    - create
    - update
    - delete
    - patch
    - watch
- apiGroups:
    - policy
  resources:
    - podsecuritypolicies
  verbs:
    - get
    - create
    - update
    - delete
    - use
- apiGroups:
    - operator.tekton.dev
  resources:
    - '*'
    - tektonaddons
  verbs:
    - get
    - list
    - create
    - update
    - delete
    - deletecollection
    - patch
    - watch
- apiGroups:
    - tekton.dev
  resources:
    - tasks
    - clustertasks
    - taskruns
    - pipelines
    - pipelineruns
    - pipelineresources
    - conditions
    - tasks/status
    - clustertasks/status
    - taskruns/status
    - pipelines/status
    - pipelineruns/status
    - pipelineresources/status
    - taskruns/finalizers
    - pipelineruns/finalizers
    - runs
    - runs/status
    - runs/finalizers
  verbs:
    - get
    - list
    - create
    - update
    - delete
    - deletecollection
    - patch
    - watch
- apiGroups:
    - triggers.tekton.dev
    - operator.tekton.dev
  resources:
    - '*'
  verbs:
    - add
    - get
    - list
    - create
    - update
    - delete
    - deletecollection
    - patch
    - watch
- apiGroups:
    - dashboard.tekton.dev
  resources:
    - '*'
    - tektonaddons
    - extensions
  verbs:
    - get
    - list
    - create
    - update
    - delete
    - deletecollection
    - patch
    - watch
- apiGroups:
    - security.openshift.io
  resources:
    - securitycontextconstraints
  verbs:
    - use
- apiGroups:
    - coordination.k8s.io
  resources:
    - leases
  verbs:
    - get
    - list
    - create
    - update
    - delete
    - patch
    - watch
- apiGroups:
    - autoscaling
  resources:
    - horizontalpodautoscalers
  verbs:
    - delete
    - deletecollection
    - create
    - patch
    - get
    - list
    - update
    - watch
- apiGroups:
    - policy
  resources:
    - poddisruptionbudgets
  verbs:
    - delete
    - deletecollection
    - create
    - patch
    - get
    - list
    - update
    - watch
- apiGroups:
    - serving.knative.dev
  resources:
    - '*'
    - '*/status'
    - '*/finalizers'
  verbs:
    - get
    - list
    - create
    - update
    - delete
    - deletecollection
    - patch
    - watch
- apiGroups:
    - batch
  resources:
    - cronjobs
  verbs:
    - delete
    - create
    - patch
    - get
    - list
    - update
    - watch
- apiGroups:
    - admissionregistration.k8s.io
  resources:
    - mutatingwebhookconfigurations
    - validatingwebhookconfigurations
  verbs:
    - delete
    - create
    - patch
    - get
    - list
    - update
    - watch
- apiGroups:
    - authentication.k8s.io
  resources:
    - tokenreviews
  verbs:
    - create
- apiGroups:
    - authorization.k8s.io
  resources:
    - subjectaccessreviews
  verbs:
    - create
- apiGroups:
    - results.tekton.dev
  resources:
    - '*'
  verbs:
    - delete
    - deletecollection
    - create
    - patch
    - get
    - list
    - update
    - watch
- apiGroups:
  - resolution.tekton.dev
  resources:
  - resolutionrequests
  verbs:
  - get
  - list
  - watch
  - create
  - delete
{{- end }}

---
{{- if (and .Values.service.createServiceMonitor .Values.openshift.enabled) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "tekton-operator.fullname" . }}
  labels:
    {{- include "tekton-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "tekton-operator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: prometheus-k8s
    namespace: openshift-monitoring
{{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "tekton-operator.fullname" . }}
  labels:
    {{- include "tekton-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "tekton-operator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "tekton-operator.fullname" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
