---
apiVersion: console.openshift.io/v1
kind: ConsoleYAMLSample
metadata:
  name: openshift-client-snippet
spec:
  targetResource:
    apiVersion: tekton.dev/v1
    kind: Pipeline
  title: Openshift-client Task
  description: |
    OpenShift is a Kubernetes distribution from Red Hat which provides oc, the OpenShift CLI that complements kubectl for simplifying deployment and configuration applications on OpenShift.
  snippet: true
  yaml: |
    - name: deploy
      taskRef:
        resolver: cluster
        params:
        - name: kind
          value: task
        - name: name
          value: openshift-client
        - name: namespace
          value: openshift-pipelines
      params:
        - name: ARGS
          value: "help"
