apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pipelines-as-code-templates
  labels:
    app.kubernetes.io/part-of: pipelines-as-code
rules:
  # All system:authenticated users needs to have access
  # of the pipelines-as-code-templates ConfigMap even if they don't
  # have access to the other resources present in the
  # installed namespace.
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list"]
    resourceNames: ["pipelines-as-code-go-template", "pipelines-as-code-java-template", "pipelines-as-code-nodejs-template", "pipelines-as-code-python-template"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipelines-as-code-templates
  labels:
    app.kubernetes.io/part-of: pipelines-as-code
subjects:
  - kind: Group
    name: system:authenticated
    apiGroup: rbac.authorization.k8s.io
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pipelines-as-code-templates
