/*
Copyright 2020 The Tekton Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "github.com/tektoncd/operator/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// ManualApprovalGates returns a ManualApprovalGateInformer.
	ManualApprovalGates() TypedManualApprovalGateInformer
	// OpenShiftPipelinesAsCodes returns a OpenShiftPipelinesAsCodeInformer.
	OpenShiftPipelinesAsCodes() TypedOpenShiftPipelinesAsCodeInformer
	// SyncerServices returns a SyncerServiceInformer.
	SyncerServices() TypedSyncerServiceInformer
	// TektonAddons returns a TektonAddonInformer.
	TektonAddons() TypedTektonAddonInformer
	// TektonChains returns a TektonChainInformer.
	TektonChains() TypedTektonChainInformer
	// TektonConfigs returns a TektonConfigInformer.
	TektonConfigs() TypedTektonConfigInformer
	// TektonDashboards returns a TektonDashboardInformer.
	TektonDashboards() TypedTektonDashboardInformer
	// TektonInstallerSets returns a TektonInstallerSetInformer.
	TektonInstallerSets() TypedTektonInstallerSetInformer
	// TektonKueues returns a TektonKueueInformer.
	TektonKueues() TypedTektonKueueInformer
	// TektonMulticlusterProxyAAEs returns a TektonMulticlusterProxyAAEInformer.
	TektonMulticlusterProxyAAEs() TypedTektonMulticlusterProxyAAEInformer
	// TektonPipelines returns a TektonPipelineInformer.
	TektonPipelines() TypedTektonPipelineInformer
	// TektonPruners returns a TektonPrunerInformer.
	TektonPruners() TypedTektonPrunerInformer
	// TektonResults returns a TektonResultInformer.
	TektonResults() TypedTektonResultInformer
	// TektonSchedulers returns a TektonSchedulerInformer.
	TektonSchedulers() TypedTektonSchedulerInformer
	// TektonTriggers returns a TektonTriggerInformer.
	TektonTriggers() TypedTektonTriggerInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// ManualApprovalGates returns a TypedManualApprovalGateInformer.
func (v *version) ManualApprovalGates() TypedManualApprovalGateInformer {
	return &manualApprovalGateInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// OpenShiftPipelinesAsCodes returns a TypedOpenShiftPipelinesAsCodeInformer.
func (v *version) OpenShiftPipelinesAsCodes() TypedOpenShiftPipelinesAsCodeInformer {
	return &openShiftPipelinesAsCodeInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// SyncerServices returns a TypedSyncerServiceInformer.
func (v *version) SyncerServices() TypedSyncerServiceInformer {
	return &syncerServiceInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// TektonAddons returns a TypedTektonAddonInformer.
func (v *version) TektonAddons() TypedTektonAddonInformer {
	return &tektonAddonInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// TektonChains returns a TypedTektonChainInformer.
func (v *version) TektonChains() TypedTektonChainInformer {
	return &tektonChainInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// TektonConfigs returns a TypedTektonConfigInformer.
func (v *version) TektonConfigs() TypedTektonConfigInformer {
	return &tektonConfigInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// TektonDashboards returns a TypedTektonDashboardInformer.
func (v *version) TektonDashboards() TypedTektonDashboardInformer {
	return &tektonDashboardInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// TektonInstallerSets returns a TypedTektonInstallerSetInformer.
func (v *version) TektonInstallerSets() TypedTektonInstallerSetInformer {
	return &tektonInstallerSetInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// TektonKueues returns a TypedTektonKueueInformer.
func (v *version) TektonKueues() TypedTektonKueueInformer {
	return &tektonKueueInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// TektonMulticlusterProxyAAEs returns a TypedTektonMulticlusterProxyAAEInformer.
func (v *version) TektonMulticlusterProxyAAEs() TypedTektonMulticlusterProxyAAEInformer {
	return &tektonMulticlusterProxyAAEInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// TektonPipelines returns a TypedTektonPipelineInformer.
func (v *version) TektonPipelines() TypedTektonPipelineInformer {
	return &tektonPipelineInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// TektonPruners returns a TypedTektonPrunerInformer.
func (v *version) TektonPruners() TypedTektonPrunerInformer {
	return &tektonPrunerInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// TektonResults returns a TypedTektonResultInformer.
func (v *version) TektonResults() TypedTektonResultInformer {
	return &tektonResultInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// TektonSchedulers returns a TypedTektonSchedulerInformer.
func (v *version) TektonSchedulers() TypedTektonSchedulerInformer {
	return &tektonSchedulerInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// TektonTriggers returns a TypedTektonTriggerInformer.
func (v *version) TektonTriggers() TypedTektonTriggerInformer {
	return &tektonTriggerInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}
