/*
Copyright 2020 The Tekton Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apisoperatorv1alpha1 "github.com/tektoncd/operator/pkg/apis/operator/v1alpha1"
	versioned "github.com/tektoncd/operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/tektoncd/operator/pkg/client/informers/externalversions/internalinterfaces"
	operatorv1alpha1 "github.com/tektoncd/operator/pkg/client/listers/operator/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// SyncerServiceInformer provides access to a shared informer and lister for
// SyncerServices. Prefer using the type-safe variant (see [TypedSyncerServiceInformer]).
type SyncerServiceInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() operatorv1alpha1.SyncerServiceLister
}

// TypedSyncerServiceInformer provides access to a shared informer and lister for
// SyncerServices, including the type-safe TypedInformer variant.
// It is a superset of SyncerServiceInformer.
type TypedSyncerServiceInformer interface {
	Informer() cache.SharedIndexInformer
	TypedInformer() SyncerServiceIndexInformer
	Lister() operatorv1alpha1.SyncerServiceLister
}

// SyncerServiceIndexInformer is a wrapper around the underlying [cache.SharedIndexInformer]
// with type-safe variants of several methods.
type SyncerServiceIndexInformer cache.TypedSharedIndexInformer[*apisoperatorv1alpha1.SyncerService]

// SyncerServiceHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerFuncs] for SyncerService.
type SyncerServiceHandlerFuncs = cache.TypedResourceEventHandlerFuncs[*apisoperatorv1alpha1.SyncerService]

// SyncerServiceDetailedHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerDetailedFuncs] for SyncerService.
type SyncerServiceDetailedHandlerFuncs = cache.TypedResourceEventHandlerDetailedFuncs[*apisoperatorv1alpha1.SyncerService]

// SyncerServiceFilteringHandler is a specialization of [cache.TypedFilteringResourceEventHandler] for SyncerService.
type SyncerServiceFilteringHandler = cache.TypedFilteringResourceEventHandler[*apisoperatorv1alpha1.SyncerService]

// SyncerServiceIndexers is a specialization of [cache.TypedIndexers] for SyncerService.
type SyncerServiceIndexers = cache.TypedIndexers[*apisoperatorv1alpha1.SyncerService]

// DeletedSyncerService is a specialization of [cache.DeletedObject] for SyncerService.
type DeletedSyncerService = cache.DeletedObject[*apisoperatorv1alpha1.SyncerService]

type syncerServiceInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewSyncerServiceInformer constructs a new informer for SyncerService type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedSyncerServiceInformer]).
func NewSyncerServiceInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewSyncerServiceInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers})
}

// NewTypedSyncerServiceInformer constructs a new informer for SyncerService type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedSyncerServiceInformer(client versioned.Interface, resyncPeriod time.Duration, indexers SyncerServiceIndexers) SyncerServiceIndexInformer {
	return NewTypedSyncerServiceInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers)})
}

// NewFilteredSyncerServiceInformer constructs a new informer for SyncerService type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedFilteredSyncerServiceInformer]).
func NewFilteredSyncerServiceInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return NewTypedSyncerServiceInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers, TweakListOptions: tweakListOptions})
}

// NewTypedFilteredSyncerServiceInformer constructs a new informer for SyncerService type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedFilteredSyncerServiceInformer(client versioned.Interface, resyncPeriod time.Duration, indexers SyncerServiceIndexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) SyncerServiceIndexInformer {
	return NewTypedSyncerServiceInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers), TweakListOptions: tweakListOptions})
}

// NewSyncerServiceInformerWithOptions constructs a new informer for SyncerService type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedSyncerServiceInformerWithOptions]).
func NewSyncerServiceInformerWithOptions(client versioned.Interface, options internalinterfaces.InformerOptions) cache.SharedIndexInformer {
	return NewTypedSyncerServiceInformerWithOptions(client, options)
}

// NewTypedSyncerServiceInformerWithOptions constructs a new informer for SyncerService type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedSyncerServiceInformerWithOptions(client versioned.Interface, options internalinterfaces.InformerOptions) SyncerServiceIndexInformer {
	gvr := schema.GroupVersionResource{Group: "operator.tekton.dev", Version: "v1alpha1", Resource: "syncerservices"}
	identifier := options.InformerName.WithResource(gvr)
	tweakListOptions := options.TweakListOptions
	return cache.NewTypedSharedIndexInformer[*apisoperatorv1alpha1.SyncerService](cache.NewSharedIndexInformerWithOptions(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.OperatorV1alpha1().SyncerServices().List(context.Background(), opts)
			},
			WatchFunc: func(opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.OperatorV1alpha1().SyncerServices().Watch(context.Background(), opts)
			},
			ListWithContextFunc: func(ctx context.Context, opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.OperatorV1alpha1().SyncerServices().List(ctx, opts)
			},
			WatchFuncWithContext: func(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.OperatorV1alpha1().SyncerServices().Watch(ctx, opts)
			},
		}, client),
		&apisoperatorv1alpha1.SyncerService{},
		cache.SharedIndexInformerOptions{
			ResyncPeriod: options.ResyncPeriod,
			Indexers:     options.Indexers,
			Identifier:   identifier,
		},
	))
}

func (f *syncerServiceInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewTypedSyncerServiceInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, InformerName: f.factory.InformerName(), TweakListOptions: f.tweakListOptions})
}

func (f *syncerServiceInformer) Informer() cache.SharedIndexInformer {
	return f.TypedInformer()
}

func (f *syncerServiceInformer) TypedInformer() SyncerServiceIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apisoperatorv1alpha1.SyncerService](f.factory.InformerFor(&apisoperatorv1alpha1.SyncerService{}, f.defaultInformer))
}

func (f *syncerServiceInformer) Lister() operatorv1alpha1.SyncerServiceLister {
	return operatorv1alpha1.NewSyncerServiceLister(f.Informer().GetIndexer())
}

// ToTypedSyncerServiceInformer converts an untyped informer into a TypedSyncerServiceInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *SyncerService. If that is not the case, calling type-safe methods of the returned
// TypedSyncerServiceInformer leads to runtime panics. A safer alternative is to pass
// around a TypedSyncerServiceInformer instances that was obtained from a
// SharedInformerFactory.
func ToTypedSyncerServiceInformer(informer SyncerServiceInformer) TypedSyncerServiceInformer {
	if informer, ok := informer.(TypedSyncerServiceInformer); ok {
		return informer
	}
	return &syncerServiceTypedInformerAdapter{informer}
}

type syncerServiceTypedInformerAdapter struct {
	SyncerServiceInformer
}

func (a *syncerServiceTypedInformerAdapter) TypedInformer() SyncerServiceIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apisoperatorv1alpha1.SyncerService](a.Informer())
}

// ToSyncerServiceIndexInformer converts an untyped informer into a SyncerServiceIndexInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *SyncerService. If that is not the case, calling type-safe methods of the returned
// SyncerServiceIndexInformer leads to runtime panics. A safer alternative is to pass
// around a SyncerServiceIndexInformer instances that was obtained from a
// SharedInformerFactory.
func ToSyncerServiceIndexInformer(informer cache.SharedIndexInformer) SyncerServiceIndexInformer {
	if informer, ok := informer.(SyncerServiceIndexInformer); ok {
		return informer
	}
	return cache.NewTypedSharedIndexInformer[*apisoperatorv1alpha1.SyncerService](informer)
}
