/*
Copyright 2020 The Tekton Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apisoperatorv1alpha1 "github.com/tektoncd/operator/pkg/apis/operator/v1alpha1"
	versioned "github.com/tektoncd/operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/tektoncd/operator/pkg/client/informers/externalversions/internalinterfaces"
	operatorv1alpha1 "github.com/tektoncd/operator/pkg/client/listers/operator/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// TektonChainInformer provides access to a shared informer and lister for
// TektonChains. Prefer using the type-safe variant (see [TypedTektonChainInformer]).
type TektonChainInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() operatorv1alpha1.TektonChainLister
}

// TypedTektonChainInformer provides access to a shared informer and lister for
// TektonChains, including the type-safe TypedInformer variant.
// It is a superset of TektonChainInformer.
type TypedTektonChainInformer interface {
	Informer() cache.SharedIndexInformer
	TypedInformer() TektonChainIndexInformer
	Lister() operatorv1alpha1.TektonChainLister
}

// TektonChainIndexInformer is a wrapper around the underlying [cache.SharedIndexInformer]
// with type-safe variants of several methods.
type TektonChainIndexInformer cache.TypedSharedIndexInformer[*apisoperatorv1alpha1.TektonChain]

// TektonChainHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerFuncs] for TektonChain.
type TektonChainHandlerFuncs = cache.TypedResourceEventHandlerFuncs[*apisoperatorv1alpha1.TektonChain]

// TektonChainDetailedHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerDetailedFuncs] for TektonChain.
type TektonChainDetailedHandlerFuncs = cache.TypedResourceEventHandlerDetailedFuncs[*apisoperatorv1alpha1.TektonChain]

// TektonChainFilteringHandler is a specialization of [cache.TypedFilteringResourceEventHandler] for TektonChain.
type TektonChainFilteringHandler = cache.TypedFilteringResourceEventHandler[*apisoperatorv1alpha1.TektonChain]

// TektonChainIndexers is a specialization of [cache.TypedIndexers] for TektonChain.
type TektonChainIndexers = cache.TypedIndexers[*apisoperatorv1alpha1.TektonChain]

// DeletedTektonChain is a specialization of [cache.DeletedObject] for TektonChain.
type DeletedTektonChain = cache.DeletedObject[*apisoperatorv1alpha1.TektonChain]

type tektonChainInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewTektonChainInformer constructs a new informer for TektonChain type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedTektonChainInformer]).
func NewTektonChainInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewTektonChainInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers})
}

// NewTypedTektonChainInformer constructs a new informer for TektonChain type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedTektonChainInformer(client versioned.Interface, resyncPeriod time.Duration, indexers TektonChainIndexers) TektonChainIndexInformer {
	return NewTypedTektonChainInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers)})
}

// NewFilteredTektonChainInformer constructs a new informer for TektonChain type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedFilteredTektonChainInformer]).
func NewFilteredTektonChainInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return NewTypedTektonChainInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers, TweakListOptions: tweakListOptions})
}

// NewTypedFilteredTektonChainInformer constructs a new informer for TektonChain type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedFilteredTektonChainInformer(client versioned.Interface, resyncPeriod time.Duration, indexers TektonChainIndexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) TektonChainIndexInformer {
	return NewTypedTektonChainInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers), TweakListOptions: tweakListOptions})
}

// NewTektonChainInformerWithOptions constructs a new informer for TektonChain type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedTektonChainInformerWithOptions]).
func NewTektonChainInformerWithOptions(client versioned.Interface, options internalinterfaces.InformerOptions) cache.SharedIndexInformer {
	return NewTypedTektonChainInformerWithOptions(client, options)
}

// NewTypedTektonChainInformerWithOptions constructs a new informer for TektonChain type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedTektonChainInformerWithOptions(client versioned.Interface, options internalinterfaces.InformerOptions) TektonChainIndexInformer {
	gvr := schema.GroupVersionResource{Group: "operator.tekton.dev", Version: "v1alpha1", Resource: "tektonchains"}
	identifier := options.InformerName.WithResource(gvr)
	tweakListOptions := options.TweakListOptions
	return cache.NewTypedSharedIndexInformer[*apisoperatorv1alpha1.TektonChain](cache.NewSharedIndexInformerWithOptions(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.OperatorV1alpha1().TektonChains().List(context.Background(), opts)
			},
			WatchFunc: func(opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.OperatorV1alpha1().TektonChains().Watch(context.Background(), opts)
			},
			ListWithContextFunc: func(ctx context.Context, opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.OperatorV1alpha1().TektonChains().List(ctx, opts)
			},
			WatchFuncWithContext: func(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.OperatorV1alpha1().TektonChains().Watch(ctx, opts)
			},
		}, client),
		&apisoperatorv1alpha1.TektonChain{},
		cache.SharedIndexInformerOptions{
			ResyncPeriod: options.ResyncPeriod,
			Indexers:     options.Indexers,
			Identifier:   identifier,
		},
	))
}

func (f *tektonChainInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewTypedTektonChainInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, InformerName: f.factory.InformerName(), TweakListOptions: f.tweakListOptions})
}

func (f *tektonChainInformer) Informer() cache.SharedIndexInformer {
	return f.TypedInformer()
}

func (f *tektonChainInformer) TypedInformer() TektonChainIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apisoperatorv1alpha1.TektonChain](f.factory.InformerFor(&apisoperatorv1alpha1.TektonChain{}, f.defaultInformer))
}

func (f *tektonChainInformer) Lister() operatorv1alpha1.TektonChainLister {
	return operatorv1alpha1.NewTektonChainLister(f.Informer().GetIndexer())
}

// ToTypedTektonChainInformer converts an untyped informer into a TypedTektonChainInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *TektonChain. If that is not the case, calling type-safe methods of the returned
// TypedTektonChainInformer leads to runtime panics. A safer alternative is to pass
// around a TypedTektonChainInformer instances that was obtained from a
// SharedInformerFactory.
func ToTypedTektonChainInformer(informer TektonChainInformer) TypedTektonChainInformer {
	if informer, ok := informer.(TypedTektonChainInformer); ok {
		return informer
	}
	return &tektonChainTypedInformerAdapter{informer}
}

type tektonChainTypedInformerAdapter struct {
	TektonChainInformer
}

func (a *tektonChainTypedInformerAdapter) TypedInformer() TektonChainIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apisoperatorv1alpha1.TektonChain](a.Informer())
}

// ToTektonChainIndexInformer converts an untyped informer into a TektonChainIndexInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *TektonChain. If that is not the case, calling type-safe methods of the returned
// TektonChainIndexInformer leads to runtime panics. A safer alternative is to pass
// around a TektonChainIndexInformer instances that was obtained from a
// SharedInformerFactory.
func ToTektonChainIndexInformer(informer cache.SharedIndexInformer) TektonChainIndexInformer {
	if informer, ok := informer.(TektonChainIndexInformer); ok {
		return informer
	}
	return cache.NewTypedSharedIndexInformer[*apisoperatorv1alpha1.TektonChain](informer)
}
