/*
Copyright 2020 The Tekton Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apisoperatorv1alpha1 "github.com/tektoncd/operator/pkg/apis/operator/v1alpha1"
	versioned "github.com/tektoncd/operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/tektoncd/operator/pkg/client/informers/externalversions/internalinterfaces"
	operatorv1alpha1 "github.com/tektoncd/operator/pkg/client/listers/operator/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// TektonAddonInformer provides access to a shared informer and lister for
// TektonAddons. Prefer using the type-safe variant (see [TypedTektonAddonInformer]).
type TektonAddonInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() operatorv1alpha1.TektonAddonLister
}

// TypedTektonAddonInformer provides access to a shared informer and lister for
// TektonAddons, including the type-safe TypedInformer variant.
// It is a superset of TektonAddonInformer.
type TypedTektonAddonInformer interface {
	Informer() cache.SharedIndexInformer
	TypedInformer() TektonAddonIndexInformer
	Lister() operatorv1alpha1.TektonAddonLister
}

// TektonAddonIndexInformer is a wrapper around the underlying [cache.SharedIndexInformer]
// with type-safe variants of several methods.
type TektonAddonIndexInformer cache.TypedSharedIndexInformer[*apisoperatorv1alpha1.TektonAddon]

// TektonAddonHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerFuncs] for TektonAddon.
type TektonAddonHandlerFuncs = cache.TypedResourceEventHandlerFuncs[*apisoperatorv1alpha1.TektonAddon]

// TektonAddonDetailedHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerDetailedFuncs] for TektonAddon.
type TektonAddonDetailedHandlerFuncs = cache.TypedResourceEventHandlerDetailedFuncs[*apisoperatorv1alpha1.TektonAddon]

// TektonAddonFilteringHandler is a specialization of [cache.TypedFilteringResourceEventHandler] for TektonAddon.
type TektonAddonFilteringHandler = cache.TypedFilteringResourceEventHandler[*apisoperatorv1alpha1.TektonAddon]

// TektonAddonIndexers is a specialization of [cache.TypedIndexers] for TektonAddon.
type TektonAddonIndexers = cache.TypedIndexers[*apisoperatorv1alpha1.TektonAddon]

// DeletedTektonAddon is a specialization of [cache.DeletedObject] for TektonAddon.
type DeletedTektonAddon = cache.DeletedObject[*apisoperatorv1alpha1.TektonAddon]

type tektonAddonInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewTektonAddonInformer constructs a new informer for TektonAddon type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedTektonAddonInformer]).
func NewTektonAddonInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewTektonAddonInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers})
}

// NewTypedTektonAddonInformer constructs a new informer for TektonAddon type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedTektonAddonInformer(client versioned.Interface, resyncPeriod time.Duration, indexers TektonAddonIndexers) TektonAddonIndexInformer {
	return NewTypedTektonAddonInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers)})
}

// NewFilteredTektonAddonInformer constructs a new informer for TektonAddon type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedFilteredTektonAddonInformer]).
func NewFilteredTektonAddonInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return NewTypedTektonAddonInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers, TweakListOptions: tweakListOptions})
}

// NewTypedFilteredTektonAddonInformer constructs a new informer for TektonAddon type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedFilteredTektonAddonInformer(client versioned.Interface, resyncPeriod time.Duration, indexers TektonAddonIndexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) TektonAddonIndexInformer {
	return NewTypedTektonAddonInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers), TweakListOptions: tweakListOptions})
}

// NewTektonAddonInformerWithOptions constructs a new informer for TektonAddon type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedTektonAddonInformerWithOptions]).
func NewTektonAddonInformerWithOptions(client versioned.Interface, options internalinterfaces.InformerOptions) cache.SharedIndexInformer {
	return NewTypedTektonAddonInformerWithOptions(client, options)
}

// NewTypedTektonAddonInformerWithOptions constructs a new informer for TektonAddon type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedTektonAddonInformerWithOptions(client versioned.Interface, options internalinterfaces.InformerOptions) TektonAddonIndexInformer {
	gvr := schema.GroupVersionResource{Group: "operator.tekton.dev", Version: "v1alpha1", Resource: "tektonaddons"}
	identifier := options.InformerName.WithResource(gvr)
	tweakListOptions := options.TweakListOptions
	return cache.NewTypedSharedIndexInformer[*apisoperatorv1alpha1.TektonAddon](cache.NewSharedIndexInformerWithOptions(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.OperatorV1alpha1().TektonAddons().List(context.Background(), opts)
			},
			WatchFunc: func(opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.OperatorV1alpha1().TektonAddons().Watch(context.Background(), opts)
			},
			ListWithContextFunc: func(ctx context.Context, opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.OperatorV1alpha1().TektonAddons().List(ctx, opts)
			},
			WatchFuncWithContext: func(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.OperatorV1alpha1().TektonAddons().Watch(ctx, opts)
			},
		}, client),
		&apisoperatorv1alpha1.TektonAddon{},
		cache.SharedIndexInformerOptions{
			ResyncPeriod: options.ResyncPeriod,
			Indexers:     options.Indexers,
			Identifier:   identifier,
		},
	))
}

func (f *tektonAddonInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewTypedTektonAddonInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, InformerName: f.factory.InformerName(), TweakListOptions: f.tweakListOptions})
}

func (f *tektonAddonInformer) Informer() cache.SharedIndexInformer {
	return f.TypedInformer()
}

func (f *tektonAddonInformer) TypedInformer() TektonAddonIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apisoperatorv1alpha1.TektonAddon](f.factory.InformerFor(&apisoperatorv1alpha1.TektonAddon{}, f.defaultInformer))
}

func (f *tektonAddonInformer) Lister() operatorv1alpha1.TektonAddonLister {
	return operatorv1alpha1.NewTektonAddonLister(f.Informer().GetIndexer())
}

// ToTypedTektonAddonInformer converts an untyped informer into a TypedTektonAddonInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *TektonAddon. If that is not the case, calling type-safe methods of the returned
// TypedTektonAddonInformer leads to runtime panics. A safer alternative is to pass
// around a TypedTektonAddonInformer instances that was obtained from a
// SharedInformerFactory.
func ToTypedTektonAddonInformer(informer TektonAddonInformer) TypedTektonAddonInformer {
	if informer, ok := informer.(TypedTektonAddonInformer); ok {
		return informer
	}
	return &tektonAddonTypedInformerAdapter{informer}
}

type tektonAddonTypedInformerAdapter struct {
	TektonAddonInformer
}

func (a *tektonAddonTypedInformerAdapter) TypedInformer() TektonAddonIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apisoperatorv1alpha1.TektonAddon](a.Informer())
}

// ToTektonAddonIndexInformer converts an untyped informer into a TektonAddonIndexInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *TektonAddon. If that is not the case, calling type-safe methods of the returned
// TektonAddonIndexInformer leads to runtime panics. A safer alternative is to pass
// around a TektonAddonIndexInformer instances that was obtained from a
// SharedInformerFactory.
func ToTektonAddonIndexInformer(informer cache.SharedIndexInformer) TektonAddonIndexInformer {
	if informer, ok := informer.(TektonAddonIndexInformer); ok {
		return informer
	}
	return cache.NewTypedSharedIndexInformer[*apisoperatorv1alpha1.TektonAddon](informer)
}
