kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-default-openshift-pipelines-view
  namespace: openshift-pipelines
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list"]
