apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: publish-operator-release
spec:
  params:
  - name: package
    description: package to release (e.g. github.com/<org>/<project>)
    default: github.com/tektoncd/operator
  - name: images
    description: List of cmd/<kubeDistro>/* paths to be published as images
    default: "operator webhook proxy-webhook"
  - name: koExtraArgs
    description: Extra args to be passed to ko
    default: "--preserve-import-paths"
  - name: versionTag
    description: The vX.Y.Z version that the artifacts should be tagged with (including `v`)
  - name: imageRegistry
    description: The target image registry
    default: ghcr.io
  - name: imageRegistryPath
    description: The path (project) in the image registry
  - name: imageRegistryRegions
    description: The target image registry regions
    default: "us eu asia"
  - name: imageRegistryUser
    description: Username to be used to login to the container registry
    default: "_json_key"
  - name: releaseAsLatest
    description: Whether to tag and publish this release as Pipelines' latest
    default: "true"
  - name: platforms
    description: Platforms to publish for the images (e.g. linux/amd64,linux/arm64)
    default: linux/amd64,linux/arm64,linux/s390x,linux/ppc64le
  - name: serviceAccountPath
    description: The name of the service account path within the release-secret workspace
  - name: kubeDistro
    description: The kubernetes distro targeted in a build. (kubernetes, openshift ...)
    default: kubernetes
  - name: releaseFilePrefix
    description: Prefix to be added to release files
    default: ""
  workspaces:
  - name: source
    description: >-
      The workspace where the repo has been cloned. This should ideally
      be /go/src/$(params.package) however that is not possible today,
      see https://github.com/tektoncd/pipeline/issues/3786. To use this
      task on a fork of pipeline change the mountPath below
    mountPath: /go/src/github.com/tektoncd/operator
  - name: release-secret
    description: The secret that contains a service account authorized to push to the imageRegistry and to the output bucket
  - name: output
    description: The release YAML will be written to this workspace
  stepTemplate:
    env:
    - name: "PROJECT_ROOT"
      value: "$(workspaces.source.path)"
    - name: CONTAINER_REGISTRY_CREDENTIALS
      value: "$(workspaces.release-secret.path)/$(params.serviceAccountPath)"
    - name: CONTAINER_REGISTRY
      value: "$(params.imageRegistry)/$(params.imageRegistryPath)"
    - name: CONTAINER_REGISTRY_USER
      value: "$(params.imageRegistryUser)"
    - name: REGIONS
      value: "$(params.imageRegistryRegions)"
    - name: OUTPUT_RELEASE_DIR
      value: "$(workspaces.output.path)/$(params.versionTag)"
    - name: KUBE_DISTRO
      value: "$(params.kubeDistro)"
    - name: FILENAME_PREFIX
      value: "$(params.releaseFilePrefix)"
    - name: KO_EXTRA_ARGS
      value: "$(params.koExtraArgs)"
  steps:

  - name: container-registy-auth
    image: cgr.dev/chainguard/crane:latest-dev@sha256:6fc6fcdeb173c7951f038e6a7b230f586c1be05a011d9e6f9db6c614ec412c2f
    script: |
      #!/bin/sh
      set -ex

      # Login to the container registry
      DOCKER_CONFIG=$(cat ${CONTAINER_REGISTRY_CREDENTIALS} | \
        crane auth login -u ${CONTAINER_REGISTRY_USER} --password-stdin $(params.imageRegistry) 2>&1 | \
        sed 's,^.*logged in via \(.*\)$,\1,g')

      # Auth with account credentials for all regions.
      for region in ${REGIONS}
      do
        HOSTNAME=${region}.$(params.imageRegistry)
        cat ${CONTAINER_REGISTRY_CREDENTIALS} | crane auth login -u ${CONTAINER_REGISTRY_USER} --password-stdin ${HOSTNAME}
      done
      cp ${DOCKER_CONFIG} /workspace/${KUBE_DISTRO}-docker-config.json

  - name: run-kustomize-ko
    image: ghcr.io/tektoncd/plumbing/ko-gcloud:v20240920-6c2a999d36@sha256:1756ca55a09b360028695792e638a7cc366292d7aef44c926a8cb765085664c8
    env:
    - name: KO_DOCKER_REPO
      value: $(params.imageRegistry)/$(params.imageRegistryPath)
    - name: GO111MODULE
      value: "on"
    - name: GOFLAGS
      value: "-mod=vendor"
    script: |
      #!/usr/bin/env sh
      set -ex

      # Setup docker-auth
      DOCKER_CONFIG=~/.docker
      mkdir -p ${DOCKER_CONFIG}
      cp /workspace/${KUBE_DISTRO}-docker-config.json ${DOCKER_CONFIG}/config.json

      # Change to directory with our .ko.yaml
      cd ${PROJECT_ROOT}

      # For each cmd/<kubeDistro>/* directory, include a full gzipped tar of all source in
      # vendor/. This is overkill. Some deps' licenses require the source to be
      # included in the container image when they're used as a dependency.
      # Rather than trying to determine which deps have this requirement (and
      # probably get it wrong), we'll just targz up the whole vendor tree and
      # include it. As of 9/20/2019, this amounts to about 11MB of additional
      # data in each image.
      TMPDIR=$(mktemp -d)
      tar cfz ${TMPDIR}/source.tar.gz vendor/
      for d in cmd/${KUBE_DISTRO}/*; do
        if [ -d ${d}/kodata/ ]; then
          ln -s ${TMPDIR}/source.tar.gz ${d}/kodata/
        fi
      done

      # Publish images and create release.yaml
      mkdir -p $OUTPUT_RELEASE_DIR

      # Make a local git tag to make git status happy :)
      # The real "tagging" will happen with the "create-release" pipeline.
      git tag $(params.versionTag)-${KUBE_DISTRO}

      kustomize build ${PROJECT_ROOT}/config/${KUBE_DISTRO}/overlays/default | \
        ko resolve \
          --image-label=org.opencontainers.image.source=https://$(params.package) \
          --platform=$(params.platforms) ${KO_EXTRA_ARGS} \
          -t $(params.versionTag) \
          -f - > $OUTPUT_RELEASE_DIR/${FILENAME_PREFIX}release.yaml

      # Publish images and create release.notags.yaml
      # This is useful if your container runtime doesn't support the `image-reference:tag@digest` notation
      # This is currently the case for `cri-o` (and most likely others)
      kustomize build ${PROJECT_ROOT}/config/${KUBE_DISTRO}/overlays/default | \
        ko resolve \
          --image-label=org.opencontainers.image.source=https://$(params.package) \
          --platform=$(params.platforms) ${KO_EXTRA_ARGS} \
          -f - > $OUTPUT_RELEASE_DIR/${FILENAME_PREFIX}release.notags.yaml

      # Rewrite "devel" to params.versionTag
      sed -i -e 's/\(pipeline.tekton.dev\/release\): "devel"/\1: "$(params.versionTag)"/g' -e 's/\(app.kubernetes.io\/version\): "devel"/\1: "$(params.versionTag)"/g' -e 's/\(version\): "devel"/\1: "$(params.versionTag)"/g' ${OUTPUT_RELEASE_DIR}/${FILENAME_PREFIX}release.yaml
      sed -i -e 's/\(pipeline.tekton.dev\/release\): "devel"/\1: "$(params.versionTag)"/g' -e 's/\(app.kubernetes.io\/version\): "devel"/\1: "$(params.versionTag)"/g' -e 's/\(version\): "devel"/\1: "$(params.versionTag)"/g' ${OUTPUT_RELEASE_DIR}/${FILENAME_PREFIX}release.notags.yaml
  - name: koparse
    image: ghcr.io/tektoncd/plumbing/koparse@sha256:194c2ab9dce5f778ed757af13c626d6b85f15452e2c2902c79b0d0f5a0adf4d1
    script: |
      set -ex

      # Find "--preserve-import-paths" in a list of args
      function find_preserve_import_path() {
        for arg in $@; do
          if [[ "$arg" == "--preserve-import-paths" ]]; then
            return 0
          fi
        done
        return 1
      }

      # If "--preserve-import-paths" is used, include "package" in the expected path
      find_preserve_import_path \
        $(echo $KO_EXTRA_ARGS) && \
        PRESERVE_IMPORT_PATH="--preserve-path" || \
        PRESERVE_IMPORT_PATH="--no-preserve-path"

      for cmd in $(params.images)
      do
        IMAGES="${IMAGES} $(params.package)/cmd/${KUBE_DISTRO}/${cmd}:$(params.versionTag)"
      done

      # Parse the built images from the release.yaml generated by ko
      koparse \
        --path $OUTPUT_RELEASE_DIR/${FILENAME_PREFIX}release.yaml \
        --base $(params.package) \
        --container-registry ${CONTAINER_REGISTRY} \
        --images ${IMAGES} \
        ${PRESERVE_IMPORT_PATH} > /workspace/built_images

  - name: tag-images
    image: cgr.dev/chainguard/crane:latest-dev@sha256:6fc6fcdeb173c7951f038e6a7b230f586c1be05a011d9e6f9db6c614ec412c2f
    script: |
      #!/bin/sh
      set -ex

      # Setup docker-auth
      DOCKER_CONFIG=~/.docker
      mkdir -p ${DOCKER_CONFIG}
      cp /workspace/${KUBE_DISTRO}-docker-config.json ${DOCKER_CONFIG}/config.json

      # Tag the images and put them in all the regions
      for IMAGE in $(cat /workspace/built_images)
      do
        IMAGE_WITHOUT_SHA=${IMAGE%%@*}
        IMAGE_WITHOUT_SHA_AND_TAG=${IMAGE_WITHOUT_SHA%%:*}
        IMAGE_WITH_SHA=${IMAGE_WITHOUT_SHA_AND_TAG}@${IMAGE##*@}

        if [[ "$(params.releaseAsLatest)" == "true" ]]
        then
          crane cp ${IMAGE_WITH_SHA} ${IMAGE_WITHOUT_SHA_AND_TAG}:latest
        fi

        for REGION in ${REGIONS}
        do
          if [[ "$(params.releaseAsLatest)" == "true" ]]
          then
            for TAG in "latest" $(params.versionTag)
            do
              crane cp ${IMAGE_WITH_SHA} ${REGION}.${IMAGE_WITHOUT_SHA_AND_TAG}:$TAG
            done
          else
            TAG="$(params.versionTag)"
            crane cp ${IMAGE_WITH_SHA} ${REGION}.${IMAGE_WITHOUT_SHA_AND_TAG}:$TAG
          fi
        done
      done
