---
# Copyright 2025 The Tekton Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: watcher
  annotations:
    networkoperator.openshift.io/ignore-errors: ""
  name: openshift-results-watcher-monitor
  namespace: openshift-pipelines
spec:
  endpoints:
    - interval: 10s
      port: metrics
  jobLabel: app
  namespaceSelector:
    matchNames:
      - openshift-pipelines
  selector:
    matchLabels:
      app.kubernetes.io/name: tekton-results-watcher
      app.kubernetes.io/part-of: tekton-results
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: api
  annotations:
    networkoperator.openshift.io/ignore-errors: ""
  name: openshift-results-api-monitor
  namespace: openshift-pipelines
spec:
  endpoints:
    - interval: 10s
      port: prometheus
  jobLabel: app
  namespaceSelector:
    matchNames:
      - openshift-pipelines
  selector:
    matchLabels:
      app.kubernetes.io/name: tekton-results-api
      app.kubernetes.io/part-of: tekton-results
