# Copyright 2020 The Tekton Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: openshift-pipelines-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: openshift-pipelines-operator
      app: openshift-pipelines-operator
  template:
    metadata:
      labels:
        name: openshift-pipelines-operator
        app: openshift-pipelines-operator
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: openshift-pipelines-operator
      containers:
      - name: openshift-pipelines-operator-lifecycle  # all reconcilers except tektoninstallerset reconciler
        image: ko://github.com/tektoncd/operator/cmd/openshift/operator
        args:
        - "-controllers"
        - "tektonconfig,tektonpipeline,tektontrigger,tektonchain,tektonaddon,tektonresult,openshiftpipelinesascode,manualapprovalgate,tektonpruner,tektonscheduler,tektonmulticlusterproxyaae,syncerservice"
        - "-unique-process-name"
        - "tekton-operator-lifecycle"
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - "ALL"
          seccompProfile:
            type: RuntimeDefault
        env:
        - name: KUBERNETES_MIN_VERSION
          value: "v1.0.0"
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: PLATFORM
          value: "openshift"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: redhat-openshift-pipelines-operator
        - name: IMAGE_PIPELINES_PROXY
          value: ko://github.com/tektoncd/operator/cmd/openshift/proxy-webhook
        - name: IMAGE_JOB_PRUNER_TKN
          value: ghcr.io/tektoncd/plumbing/tkn@sha256:233de6c8b8583a34c2379fa98d42dba739146c9336e8d41b66030484357481ed
        - name: METRICS_DOMAIN
          value: tekton.dev/operator
        - name: VERSION
          value: "devel"
        - name: AUTOINSTALL_COMPONENTS
          valueFrom:
            configMapKeyRef:
              name: tekton-config-defaults
              key: AUTOINSTALL_COMPONENTS
        - name: DEFAULT_TARGET_NAMESPACE
          valueFrom:
            configMapKeyRef:
              name: tekton-config-defaults
              key: DEFAULT_TARGET_NAMESPACE
        - name: CONFIG_OBSERVABILITY_NAME
          value: tekton-config-observability
        - name: CONFIG_LEADERELECTION_NAME
          value: tekton-operator-controller-config-leader-election
        - name: IMAGE_ADDONS_PARAM_BUILDER_IMAGE
          value: registry.redhat.io/rhel9/buildah@sha256:b9a21eafe26e81ade7a49fe8e67192a35ce3a15a95ae71fc3b1203fcc4ea4472
        - name: IMAGE_ADDONS_PARAM_KN_IMAGE
          value: registry.redhat.io/openshift-serverless-1/kn-client-kn-rhel9@sha256:aee19896d17a431ba980564fdb73ef08ad1512f586fbdf954cecef6258f7a8df
        - name: IMAGE_ADDONS_MVN_SETTINGS
          value: registry.redhat.io/ubi9/ubi-minimal@sha256:463cae32c6f6f5594b11a5c22de275016bd8545ce58a6373388e8b24f13fc15c
        - name: IMAGE_ADDONS_SKOPEO_COPY
          value: registry.redhat.io/rhel9/skopeo@sha256:028883ab919f8288b2a542f53a7fa07ac1294887bcebd34d620dc75c089a846b
        - name: IMAGE_ADDONS_GENERATE
          value: registry.redhat.io/source-to-image/source-to-image-rhel9@sha256:718e59d9aacacbaa16be3ae247bdb8582dc4fd9cbe0c5314dfdfc8f22e4f3578
        - name: IMAGE_ADDONS_GEN_ENV_FILE
          value: registry.redhat.io/source-to-image/source-to-image-rhel9@sha256:718e59d9aacacbaa16be3ae247bdb8582dc4fd9cbe0c5314dfdfc8f22e4f3578
        - name: IMAGE_ADDONS_PARAM_MAVEN_IMAGE
          value: registry.redhat.io/ubi9/openjdk-17@sha256:052c0ab499cfbb24b20339394778dfe6402a66b42398c8e59c87697b9b3f0a42
        - name: IMAGE_ADDONS_OC
          value: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
      - name: openshift-pipelines-operator-cluster-operations  # tektoninstallerset reconciler
        image: ko://github.com/tektoncd/operator/cmd/openshift/operator
        args:
        - "-controllers"
        - "tektoninstallerset"
        - "-unique-process-name"
        - "tekton-operator-cluster-operations"
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - "ALL"
          seccompProfile:
            type: RuntimeDefault
        env:
          - name: KUBERNETES_MIN_VERSION
            value: "v1.0.0"
          - name: SYSTEM_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: OPERATOR_NAME
            value: redhat-openshift-pipelines-operator
          - name: PROFILING_PORT
            value: "9009"
          - name: VERSION
            value: "devel"
          - name: METRICS_DOMAIN
            value: tekton.dev/operator
          - name: CONFIG_LEADERELECTION_NAME
            value: tekton-operator-controller-config-leader-election
