# Copyright 2020 The Tekton Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: openshift-pipelines-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: openshift-pipelines-operator
      app: openshift-pipelines-operator
  template:
    metadata:
      labels:
        name: openshift-pipelines-operator
        app: openshift-pipelines-operator
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: openshift-pipelines-operator
      containers:
      - name: openshift-pipelines-operator-lifecycle  # all reconcilers except tektoninstallerset reconciler
        image: ko://github.com/tektoncd/operator/cmd/openshift/operator
        args:
        - "-controllers"
        - "tektonconfig,tektonpipeline,tektontrigger,tektonhub,tektonchain,tektonaddon,tektonresult,openshiftpipelinesascode,manualapprovalgate,tektonpruner,tektonscheduler,tektonmulticlusterproxyaae,syncerservice"
        - "-unique-process-name"
        - "tekton-operator-lifecycle"
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - "ALL"
          seccompProfile:
            type: RuntimeDefault
        env:
        - name: KUBERNETES_MIN_VERSION
          value: "v1.0.0"
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: PLATFORM
          value: "openshift"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: redhat-openshift-pipelines-operator
        - name: IMAGE_PIPELINES_PROXY
          value: ko://github.com/tektoncd/operator/cmd/openshift/proxy-webhook
        - name: IMAGE_JOB_PRUNER_TKN
          value: ghcr.io/tektoncd/plumbing/tkn@sha256:233de6c8b8583a34c2379fa98d42dba739146c9336e8d41b66030484357481ed
        - name: METRICS_DOMAIN
          value: tekton.dev/operator
        - name: VERSION
          value: "devel"
        - name: AUTOINSTALL_COMPONENTS
          valueFrom:
            configMapKeyRef:
              name: tekton-config-defaults
              key: AUTOINSTALL_COMPONENTS
        - name: DEFAULT_TARGET_NAMESPACE
          valueFrom:
            configMapKeyRef:
              name: tekton-config-defaults
              key: DEFAULT_TARGET_NAMESPACE
        - name: CONFIG_OBSERVABILITY_NAME
          value: tekton-config-observability
        - name: CONFIG_LEADERELECTION_NAME
          value: tekton-operator-controller-config-leader-election
        - name: IMAGE_HUB_TEKTON_HUB_DB
          value: registry.redhat.io/rhel9/postgresql-15@sha256:327d89e4b62d990dbf55d3c78f271373747816c2e0ab3c943fb016cdcf12f9b5
        - name: IMAGE_ADDONS_PARAM_BUILDER_IMAGE
          value: registry.redhat.io/rhel9/buildah@sha256:f0432e506a8aea892078322518aedeb12e0f17504dbc29fd293cd8cda06e7f73
        - name: IMAGE_ADDONS_PARAM_KN_IMAGE
          value: registry.redhat.io/openshift-serverless-1/kn-client-kn-rhel9@sha256:aee19896d17a431ba980564fdb73ef08ad1512f586fbdf954cecef6258f7a8df
        - name: IMAGE_ADDONS_MVN_SETTINGS
          value: registry.redhat.io/ubi9/ubi-minimal@sha256:5b74fce9d6e629942a0c6dc0f546c193e70d7f974d999a48c948c53dd3d36362
        - name: IMAGE_ADDONS_SKOPEO_COPY
          value: registry.redhat.io/rhel9/skopeo@sha256:ecc4e3b3aeaadac17f9c0922ea2d7251303761a2695f7e9e08b6d89c7f057388
        - name: IMAGE_ADDONS_GENERATE
          value: registry.redhat.io/source-to-image/source-to-image-rhel9@sha256:70293cb8a80aa548933ff5f502bac89945a5cd08801c4ca3aac08a10dd01f62f
        - name: IMAGE_ADDONS_GEN_ENV_FILE
          value: registry.redhat.io/source-to-image/source-to-image-rhel9@sha256:70293cb8a80aa548933ff5f502bac89945a5cd08801c4ca3aac08a10dd01f62f
        - name: IMAGE_ADDONS_PARAM_MAVEN_IMAGE
          value: registry.redhat.io/ubi9/openjdk-17@sha256:4a1c11377fcd260a2fecfe0ec01e143cc05150c3d9b70b018cdcc68c6f5667a9
        - name: IMAGE_ADDONS_OC
          value: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
      - name: openshift-pipelines-operator-cluster-operations  # tektoninstallerset reconciler
        image: ko://github.com/tektoncd/operator/cmd/openshift/operator
        args:
        - "-controllers"
        - "tektoninstallerset"
        - "-unique-process-name"
        - "tekton-operator-cluster-operations"
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - "ALL"
          seccompProfile:
            type: RuntimeDefault
        env:
          - name: KUBERNETES_MIN_VERSION
            value: "v1.0.0"
          - name: SYSTEM_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: OPERATOR_NAME
            value: redhat-openshift-pipelines-operator
          - name: PROFILING_PORT
            value: "9009"
          - name: VERSION
            value: "devel"
          - name: METRICS_DOMAIN
            value: tekton.dev/operator
          - name: CONFIG_LEADERELECTION_NAME
            value: tekton-operator-controller-config-leader-election
