apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: tekton-result-read-role
rules:
- apiGroups:
  - operator.tekton.dev
  resources:
  - tektonresults
  verbs:
  - get
  - watch
  - list
