apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-ecosystem-task-list-binding
  namespace: openshift-pipelines
subjects:
  # Giving all system:authenticated users the access to the
  # tasks present in openshift-pipelines namespace
  - kind: Group
    name: system:authenticated
    apiGroup: rbac.authorization.k8s.io
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tekton-ecosystem-task-list-role
