/*
Copyright 2020 The Tekton Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	operatorv1alpha1 "github.com/tektoncd/operator/pkg/apis/operator/v1alpha1"
	scheme "github.com/tektoncd/operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// TektonKueuesGetter has a method to return a TektonKueueInterface.
// A group's client should implement this interface.
type TektonKueuesGetter interface {
	TektonKueues() TektonKueueInterface
}

// TektonKueueInterface has methods to work with TektonKueue resources.
type TektonKueueInterface interface {
	Create(ctx context.Context, tektonKueue *operatorv1alpha1.TektonKueue, opts v1.CreateOptions) (*operatorv1alpha1.TektonKueue, error)
	Update(ctx context.Context, tektonKueue *operatorv1alpha1.TektonKueue, opts v1.UpdateOptions) (*operatorv1alpha1.TektonKueue, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, tektonKueue *operatorv1alpha1.TektonKueue, opts v1.UpdateOptions) (*operatorv1alpha1.TektonKueue, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*operatorv1alpha1.TektonKueue, error)
	List(ctx context.Context, opts v1.ListOptions) (*operatorv1alpha1.TektonKueueList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *operatorv1alpha1.TektonKueue, err error)
	TektonKueueExpansion
}

// tektonKueues implements TektonKueueInterface
type tektonKueues struct {
	*gentype.ClientWithList[*operatorv1alpha1.TektonKueue, *operatorv1alpha1.TektonKueueList]
}

// newTektonKueues returns a TektonKueues
func newTektonKueues(c *OperatorV1alpha1Client) *tektonKueues {
	return &tektonKueues{
		gentype.NewClientWithList[*operatorv1alpha1.TektonKueue, *operatorv1alpha1.TektonKueueList](
			"tektonkueues",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *operatorv1alpha1.TektonKueue { return &operatorv1alpha1.TektonKueue{} },
			func() *operatorv1alpha1.TektonKueueList { return &operatorv1alpha1.TektonKueueList{} },
		),
	}
}
