/*
Copyright 2020 The Tekton Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/tektoncd/operator/pkg/apis/operator/v1alpha1"
	scheme "github.com/tektoncd/operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// TektonChainsesGetter has a method to return a TektonChainsInterface.
// A group's client should implement this interface.
type TektonChainsesGetter interface {
	TektonChainses() TektonChainsInterface
}

// TektonChainsInterface has methods to work with TektonChains resources.
type TektonChainsInterface interface {
	Create(ctx context.Context, tektonChains *v1alpha1.TektonChains, opts v1.CreateOptions) (*v1alpha1.TektonChains, error)
	Update(ctx context.Context, tektonChains *v1alpha1.TektonChains, opts v1.UpdateOptions) (*v1alpha1.TektonChains, error)
	UpdateStatus(ctx context.Context, tektonChains *v1alpha1.TektonChains, opts v1.UpdateOptions) (*v1alpha1.TektonChains, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.TektonChains, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.TektonChainsList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.TektonChains, err error)
	TektonChainsExpansion
}

// tektonChainses implements TektonChainsInterface
type tektonChainses struct {
	client rest.Interface
}

// newTektonChainses returns a TektonChainses
func newTektonChainses(c *OperatorV1alpha1Client) *tektonChainses {
	return &tektonChainses{
		client: c.RESTClient(),
	}
}

// Get takes name of the tektonChains, and returns the corresponding tektonChains object, and an error if there is any.
func (c *tektonChainses) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.TektonChains, err error) {
	result = &v1alpha1.TektonChains{}
	err = c.client.Get().
		Resource("tektonchainses").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of TektonChainses that match those selectors.
func (c *tektonChainses) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.TektonChainsList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.TektonChainsList{}
	err = c.client.Get().
		Resource("tektonchainses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested tektonChainses.
func (c *tektonChainses) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("tektonchainses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a tektonChains and creates it.  Returns the server's representation of the tektonChains, and an error, if there is any.
func (c *tektonChainses) Create(ctx context.Context, tektonChains *v1alpha1.TektonChains, opts v1.CreateOptions) (result *v1alpha1.TektonChains, err error) {
	result = &v1alpha1.TektonChains{}
	err = c.client.Post().
		Resource("tektonchainses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(tektonChains).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a tektonChains and updates it. Returns the server's representation of the tektonChains, and an error, if there is any.
func (c *tektonChainses) Update(ctx context.Context, tektonChains *v1alpha1.TektonChains, opts v1.UpdateOptions) (result *v1alpha1.TektonChains, err error) {
	result = &v1alpha1.TektonChains{}
	err = c.client.Put().
		Resource("tektonchainses").
		Name(tektonChains.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(tektonChains).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *tektonChainses) UpdateStatus(ctx context.Context, tektonChains *v1alpha1.TektonChains, opts v1.UpdateOptions) (result *v1alpha1.TektonChains, err error) {
	result = &v1alpha1.TektonChains{}
	err = c.client.Put().
		Resource("tektonchainses").
		Name(tektonChains.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(tektonChains).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the tektonChains and deletes it. Returns an error if one occurs.
func (c *tektonChainses) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("tektonchainses").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *tektonChainses) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("tektonchainses").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched tektonChains.
func (c *tektonChainses) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.TektonChains, err error) {
	result = &v1alpha1.TektonChains{}
	err = c.client.Patch(pt).
		Resource("tektonchainses").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
