/*
Copyright 2020 The Tekton Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	operatorv1alpha1 "github.com/tektoncd/operator/pkg/apis/operator/v1alpha1"
	scheme "github.com/tektoncd/operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// TektonResultsGetter has a method to return a TektonResultInterface.
// A group's client should implement this interface.
type TektonResultsGetter interface {
	TektonResults() TektonResultInterface
}

// TektonResultInterface has methods to work with TektonResult resources.
type TektonResultInterface interface {
	Create(ctx context.Context, tektonResult *operatorv1alpha1.TektonResult, opts v1.CreateOptions) (*operatorv1alpha1.TektonResult, error)
	Update(ctx context.Context, tektonResult *operatorv1alpha1.TektonResult, opts v1.UpdateOptions) (*operatorv1alpha1.TektonResult, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, tektonResult *operatorv1alpha1.TektonResult, opts v1.UpdateOptions) (*operatorv1alpha1.TektonResult, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*operatorv1alpha1.TektonResult, error)
	List(ctx context.Context, opts v1.ListOptions) (*operatorv1alpha1.TektonResultList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *operatorv1alpha1.TektonResult, err error)
	TektonResultExpansion
}

// tektonResults implements TektonResultInterface
type tektonResults struct {
	*gentype.ClientWithList[*operatorv1alpha1.TektonResult, *operatorv1alpha1.TektonResultList]
}

// newTektonResults returns a TektonResults
func newTektonResults(c *OperatorV1alpha1Client) *tektonResults {
	return &tektonResults{
		gentype.NewClientWithList[*operatorv1alpha1.TektonResult, *operatorv1alpha1.TektonResultList](
			"tektonresults",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *operatorv1alpha1.TektonResult { return &operatorv1alpha1.TektonResult{} },
			func() *operatorv1alpha1.TektonResultList { return &operatorv1alpha1.TektonResultList{} },
		),
	}
}
