/*
Copyright 2020 The Tekton Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	operatorv1alpha1 "github.com/tektoncd/operator/pkg/apis/operator/v1alpha1"
	scheme "github.com/tektoncd/operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// TektonInstallerSetsGetter has a method to return a TektonInstallerSetInterface.
// A group's client should implement this interface.
type TektonInstallerSetsGetter interface {
	TektonInstallerSets() TektonInstallerSetInterface
}

// TektonInstallerSetInterface has methods to work with TektonInstallerSet resources.
type TektonInstallerSetInterface interface {
	Create(ctx context.Context, tektonInstallerSet *operatorv1alpha1.TektonInstallerSet, opts v1.CreateOptions) (*operatorv1alpha1.TektonInstallerSet, error)
	Update(ctx context.Context, tektonInstallerSet *operatorv1alpha1.TektonInstallerSet, opts v1.UpdateOptions) (*operatorv1alpha1.TektonInstallerSet, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, tektonInstallerSet *operatorv1alpha1.TektonInstallerSet, opts v1.UpdateOptions) (*operatorv1alpha1.TektonInstallerSet, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*operatorv1alpha1.TektonInstallerSet, error)
	List(ctx context.Context, opts v1.ListOptions) (*operatorv1alpha1.TektonInstallerSetList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *operatorv1alpha1.TektonInstallerSet, err error)
	TektonInstallerSetExpansion
}

// tektonInstallerSets implements TektonInstallerSetInterface
type tektonInstallerSets struct {
	*gentype.ClientWithList[*operatorv1alpha1.TektonInstallerSet, *operatorv1alpha1.TektonInstallerSetList]
}

// newTektonInstallerSets returns a TektonInstallerSets
func newTektonInstallerSets(c *OperatorV1alpha1Client) *tektonInstallerSets {
	return &tektonInstallerSets{
		gentype.NewClientWithList[*operatorv1alpha1.TektonInstallerSet, *operatorv1alpha1.TektonInstallerSetList](
			"tektoninstallersets",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *operatorv1alpha1.TektonInstallerSet { return &operatorv1alpha1.TektonInstallerSet{} },
			func() *operatorv1alpha1.TektonInstallerSetList { return &operatorv1alpha1.TektonInstallerSetList{} },
		),
	}
}
