/*
Copyright 2020 The Tekton Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/tektoncd/operator/pkg/apis/operator/v1alpha1"
	scheme "github.com/tektoncd/operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// TektonDashboardsGetter has a method to return a TektonDashboardInterface.
// A group's client should implement this interface.
type TektonDashboardsGetter interface {
	TektonDashboards() TektonDashboardInterface
}

// TektonDashboardInterface has methods to work with TektonDashboard resources.
type TektonDashboardInterface interface {
	Create(*v1alpha1.TektonDashboard) (*v1alpha1.TektonDashboard, error)
	Update(*v1alpha1.TektonDashboard) (*v1alpha1.TektonDashboard, error)
	UpdateStatus(*v1alpha1.TektonDashboard) (*v1alpha1.TektonDashboard, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.TektonDashboard, error)
	List(opts v1.ListOptions) (*v1alpha1.TektonDashboardList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.TektonDashboard, err error)
	TektonDashboardExpansion
}

// tektonDashboards implements TektonDashboardInterface
type tektonDashboards struct {
	client rest.Interface
}

// newTektonDashboards returns a TektonDashboards
func newTektonDashboards(c *OperatorV1alpha1Client) *tektonDashboards {
	return &tektonDashboards{
		client: c.RESTClient(),
	}
}

// Get takes name of the tektonDashboard, and returns the corresponding tektonDashboard object, and an error if there is any.
func (c *tektonDashboards) Get(name string, options v1.GetOptions) (result *v1alpha1.TektonDashboard, err error) {
	result = &v1alpha1.TektonDashboard{}
	err = c.client.Get().
		Resource("tektondashboards").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of TektonDashboards that match those selectors.
func (c *tektonDashboards) List(opts v1.ListOptions) (result *v1alpha1.TektonDashboardList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.TektonDashboardList{}
	err = c.client.Get().
		Resource("tektondashboards").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested tektonDashboards.
func (c *tektonDashboards) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("tektondashboards").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a tektonDashboard and creates it.  Returns the server's representation of the tektonDashboard, and an error, if there is any.
func (c *tektonDashboards) Create(tektonDashboard *v1alpha1.TektonDashboard) (result *v1alpha1.TektonDashboard, err error) {
	result = &v1alpha1.TektonDashboard{}
	err = c.client.Post().
		Resource("tektondashboards").
		Body(tektonDashboard).
		Do().
		Into(result)
	return
}

// Update takes the representation of a tektonDashboard and updates it. Returns the server's representation of the tektonDashboard, and an error, if there is any.
func (c *tektonDashboards) Update(tektonDashboard *v1alpha1.TektonDashboard) (result *v1alpha1.TektonDashboard, err error) {
	result = &v1alpha1.TektonDashboard{}
	err = c.client.Put().
		Resource("tektondashboards").
		Name(tektonDashboard.Name).
		Body(tektonDashboard).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *tektonDashboards) UpdateStatus(tektonDashboard *v1alpha1.TektonDashboard) (result *v1alpha1.TektonDashboard, err error) {
	result = &v1alpha1.TektonDashboard{}
	err = c.client.Put().
		Resource("tektondashboards").
		Name(tektonDashboard.Name).
		SubResource("status").
		Body(tektonDashboard).
		Do().
		Into(result)
	return
}

// Delete takes name of the tektonDashboard and deletes it. Returns an error if one occurs.
func (c *tektonDashboards) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("tektondashboards").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *tektonDashboards) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("tektondashboards").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched tektonDashboard.
func (c *tektonDashboards) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.TektonDashboard, err error) {
	result = &v1alpha1.TektonDashboard{}
	err = c.client.Patch(pt).
		Resource("tektondashboards").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
