/*
Copyright 2020 The Tekton Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/tektoncd/operator/pkg/apis/operator/v1alpha1"
	scheme "github.com/tektoncd/operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// TektonPrunersGetter has a method to return a TektonPrunerInterface.
// A group's client should implement this interface.
type TektonPrunersGetter interface {
	TektonPruners() TektonPrunerInterface
}

// TektonPrunerInterface has methods to work with TektonPruner resources.
type TektonPrunerInterface interface {
	Create(ctx context.Context, tektonPruner *v1alpha1.TektonPruner, opts v1.CreateOptions) (*v1alpha1.TektonPruner, error)
	Update(ctx context.Context, tektonPruner *v1alpha1.TektonPruner, opts v1.UpdateOptions) (*v1alpha1.TektonPruner, error)
	UpdateStatus(ctx context.Context, tektonPruner *v1alpha1.TektonPruner, opts v1.UpdateOptions) (*v1alpha1.TektonPruner, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.TektonPruner, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.TektonPrunerList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.TektonPruner, err error)
	TektonPrunerExpansion
}

// tektonPruners implements TektonPrunerInterface
type tektonPruners struct {
	client rest.Interface
}

// newTektonPruners returns a TektonPruners
func newTektonPruners(c *OperatorV1alpha1Client) *tektonPruners {
	return &tektonPruners{
		client: c.RESTClient(),
	}
}

// Get takes name of the tektonPruner, and returns the corresponding tektonPruner object, and an error if there is any.
func (c *tektonPruners) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.TektonPruner, err error) {
	result = &v1alpha1.TektonPruner{}
	err = c.client.Get().
		Resource("tektonpruners").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of TektonPruners that match those selectors.
func (c *tektonPruners) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.TektonPrunerList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.TektonPrunerList{}
	err = c.client.Get().
		Resource("tektonpruners").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested tektonPruners.
func (c *tektonPruners) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("tektonpruners").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a tektonPruner and creates it.  Returns the server's representation of the tektonPruner, and an error, if there is any.
func (c *tektonPruners) Create(ctx context.Context, tektonPruner *v1alpha1.TektonPruner, opts v1.CreateOptions) (result *v1alpha1.TektonPruner, err error) {
	result = &v1alpha1.TektonPruner{}
	err = c.client.Post().
		Resource("tektonpruners").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(tektonPruner).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a tektonPruner and updates it. Returns the server's representation of the tektonPruner, and an error, if there is any.
func (c *tektonPruners) Update(ctx context.Context, tektonPruner *v1alpha1.TektonPruner, opts v1.UpdateOptions) (result *v1alpha1.TektonPruner, err error) {
	result = &v1alpha1.TektonPruner{}
	err = c.client.Put().
		Resource("tektonpruners").
		Name(tektonPruner.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(tektonPruner).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *tektonPruners) UpdateStatus(ctx context.Context, tektonPruner *v1alpha1.TektonPruner, opts v1.UpdateOptions) (result *v1alpha1.TektonPruner, err error) {
	result = &v1alpha1.TektonPruner{}
	err = c.client.Put().
		Resource("tektonpruners").
		Name(tektonPruner.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(tektonPruner).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the tektonPruner and deletes it. Returns an error if one occurs.
func (c *tektonPruners) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("tektonpruners").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *tektonPruners) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("tektonpruners").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched tektonPruner.
func (c *tektonPruners) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.TektonPruner, err error) {
	result = &v1alpha1.TektonPruner{}
	err = c.client.Patch(pt).
		Resource("tektonpruners").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
