/*
Copyright 2020 The Tekton Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/tektoncd/operator/pkg/apis/operator/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeTektonChainses implements TektonChainsInterface
type FakeTektonChainses struct {
	Fake *FakeOperatorV1alpha1
}

var tektonchainsesResource = schema.GroupVersionResource{Group: "operator.tekton.dev", Version: "v1alpha1", Resource: "tektonchainses"}

var tektonchainsesKind = schema.GroupVersionKind{Group: "operator.tekton.dev", Version: "v1alpha1", Kind: "TektonChains"}

// Get takes name of the tektonChains, and returns the corresponding tektonChains object, and an error if there is any.
func (c *FakeTektonChainses) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.TektonChains, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(tektonchainsesResource, name), &v1alpha1.TektonChains{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TektonChains), err
}

// List takes label and field selectors, and returns the list of TektonChainses that match those selectors.
func (c *FakeTektonChainses) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.TektonChainsList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(tektonchainsesResource, tektonchainsesKind, opts), &v1alpha1.TektonChainsList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.TektonChainsList{ListMeta: obj.(*v1alpha1.TektonChainsList).ListMeta}
	for _, item := range obj.(*v1alpha1.TektonChainsList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested tektonChainses.
func (c *FakeTektonChainses) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(tektonchainsesResource, opts))
}

// Create takes the representation of a tektonChains and creates it.  Returns the server's representation of the tektonChains, and an error, if there is any.
func (c *FakeTektonChainses) Create(ctx context.Context, tektonChains *v1alpha1.TektonChains, opts v1.CreateOptions) (result *v1alpha1.TektonChains, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(tektonchainsesResource, tektonChains), &v1alpha1.TektonChains{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TektonChains), err
}

// Update takes the representation of a tektonChains and updates it. Returns the server's representation of the tektonChains, and an error, if there is any.
func (c *FakeTektonChainses) Update(ctx context.Context, tektonChains *v1alpha1.TektonChains, opts v1.UpdateOptions) (result *v1alpha1.TektonChains, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(tektonchainsesResource, tektonChains), &v1alpha1.TektonChains{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TektonChains), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeTektonChainses) UpdateStatus(ctx context.Context, tektonChains *v1alpha1.TektonChains, opts v1.UpdateOptions) (*v1alpha1.TektonChains, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(tektonchainsesResource, "status", tektonChains), &v1alpha1.TektonChains{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TektonChains), err
}

// Delete takes name of the tektonChains and deletes it. Returns an error if one occurs.
func (c *FakeTektonChainses) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(tektonchainsesResource, name), &v1alpha1.TektonChains{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeTektonChainses) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(tektonchainsesResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.TektonChainsList{})
	return err
}

// Patch applies the patch and returns the patched tektonChains.
func (c *FakeTektonChainses) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.TektonChains, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(tektonchainsesResource, name, pt, data, subresources...), &v1alpha1.TektonChains{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TektonChains), err
}
