/*
Copyright 2020 The Tekton Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/tektoncd/operator/pkg/apis/operator/v1alpha1"
	operatorv1alpha1 "github.com/tektoncd/operator/pkg/client/clientset/versioned/typed/operator/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeTektonChains implements TektonChainInterface
type fakeTektonChains struct {
	*gentype.FakeClientWithList[*v1alpha1.TektonChain, *v1alpha1.TektonChainList]
	Fake *FakeOperatorV1alpha1
}

func newFakeTektonChains(fake *FakeOperatorV1alpha1) operatorv1alpha1.TektonChainInterface {
	return &fakeTektonChains{
		gentype.NewFakeClientWithList[*v1alpha1.TektonChain, *v1alpha1.TektonChainList](
			fake.Fake,
			"",
			v1alpha1.SchemeGroupVersion.WithResource("tektonchains"),
			v1alpha1.SchemeGroupVersion.WithKind("TektonChain"),
			func() *v1alpha1.TektonChain { return &v1alpha1.TektonChain{} },
			func() *v1alpha1.TektonChainList { return &v1alpha1.TektonChainList{} },
			func(dst, src *v1alpha1.TektonChainList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.TektonChainList) []*v1alpha1.TektonChain {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.TektonChainList, items []*v1alpha1.TektonChain) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
