/*
Copyright 2020 The Tekton Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/tektoncd/operator/pkg/apis/operator/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeManualApprovalGates implements ManualApprovalGateInterface
type FakeManualApprovalGates struct {
	Fake *FakeOperatorV1alpha1
}

var manualapprovalgatesResource = v1alpha1.SchemeGroupVersion.WithResource("manualapprovalgates")

var manualapprovalgatesKind = v1alpha1.SchemeGroupVersion.WithKind("ManualApprovalGate")

// Get takes name of the manualApprovalGate, and returns the corresponding manualApprovalGate object, and an error if there is any.
func (c *FakeManualApprovalGates) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ManualApprovalGate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(manualapprovalgatesResource, name), &v1alpha1.ManualApprovalGate{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ManualApprovalGate), err
}

// List takes label and field selectors, and returns the list of ManualApprovalGates that match those selectors.
func (c *FakeManualApprovalGates) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ManualApprovalGateList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(manualapprovalgatesResource, manualapprovalgatesKind, opts), &v1alpha1.ManualApprovalGateList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ManualApprovalGateList{ListMeta: obj.(*v1alpha1.ManualApprovalGateList).ListMeta}
	for _, item := range obj.(*v1alpha1.ManualApprovalGateList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested manualApprovalGates.
func (c *FakeManualApprovalGates) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(manualapprovalgatesResource, opts))
}

// Create takes the representation of a manualApprovalGate and creates it.  Returns the server's representation of the manualApprovalGate, and an error, if there is any.
func (c *FakeManualApprovalGates) Create(ctx context.Context, manualApprovalGate *v1alpha1.ManualApprovalGate, opts v1.CreateOptions) (result *v1alpha1.ManualApprovalGate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(manualapprovalgatesResource, manualApprovalGate), &v1alpha1.ManualApprovalGate{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ManualApprovalGate), err
}

// Update takes the representation of a manualApprovalGate and updates it. Returns the server's representation of the manualApprovalGate, and an error, if there is any.
func (c *FakeManualApprovalGates) Update(ctx context.Context, manualApprovalGate *v1alpha1.ManualApprovalGate, opts v1.UpdateOptions) (result *v1alpha1.ManualApprovalGate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(manualapprovalgatesResource, manualApprovalGate), &v1alpha1.ManualApprovalGate{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ManualApprovalGate), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeManualApprovalGates) UpdateStatus(ctx context.Context, manualApprovalGate *v1alpha1.ManualApprovalGate, opts v1.UpdateOptions) (*v1alpha1.ManualApprovalGate, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(manualapprovalgatesResource, "status", manualApprovalGate), &v1alpha1.ManualApprovalGate{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ManualApprovalGate), err
}

// Delete takes name of the manualApprovalGate and deletes it. Returns an error if one occurs.
func (c *FakeManualApprovalGates) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(manualapprovalgatesResource, name, opts), &v1alpha1.ManualApprovalGate{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeManualApprovalGates) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(manualapprovalgatesResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ManualApprovalGateList{})
	return err
}

// Patch applies the patch and returns the patched manualApprovalGate.
func (c *FakeManualApprovalGates) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ManualApprovalGate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(manualapprovalgatesResource, name, pt, data, subresources...), &v1alpha1.ManualApprovalGate{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ManualApprovalGate), err
}
