apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tekton-ecosystem-stepaction-list-role
  namespace: openshift-pipelines
rules:
  - apiGroups:
      - tekton.dev
    resources:
      - stepactions
    verbs:
      - get
      - list
