platform: "kubernetes"
operator-packagename: "tektoncd-operator"
image-substitutions:
- image: ko://github.com/tektoncd/operator/cmd/kubernetes/operator:devel
  replaceLocations:
    containerTargets:
    - deploymentName: tekton-operator
      containerName: tekton-operator-lifecycle
- image: ko://github.com/tektoncd/operator/cmd/kubernetes/webhook:develEnv
  replaceLocations:
    envTargets:
    - deploymentName: tekton-operator
      containerName: tekton-operator-lifecycle
      envKeys:
      - IMAGE_PIPELINES_PROXY
- image: gcr.io/tekton-releases/dogfooding/tkn@sha256:64886334a4fd2a9fef496e83e248d66159c05691abb66bf5e6887ba3845f61d8
  replaceLocations:
    envTargets:
    - deploymentName: tekton-operator
      containerName: tekton-operator-lifecycle
      envKeys:
      - IMAGE_JOB_PRUNER_TKN
- image: ko://github.com/tektoncd/operator/cmd/kubernetes/webhook
  replaceLocations:
    containerTargets:
    - deploymentName: tekton-operator-webhook
      containerName: tekton-operator-lifecycle-webhook

# add thrid party images which are not replaced by operator
# but pulled directly by tasks here
defaultRelatedImages: []
#  - image: "" ##<imagename>:<tag> or <imagename>@<sha>
#    name: "" # ENV key name value
