name: Update Tekton Task Versions

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight
  workflow_dispatch: {}  # Allows manual trigger

permissions: {}

jobs:
  update-task-versions:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'tektoncd'  # do not run this elsewhere
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout Operator Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          persist-credentials: false

      - name: Clone TektonCD Catalog (p branch)
        run: |
          git clone --branch p https://github.com/openshift-pipelines/tektoncd-catalog.git ../tektoncd-catalog

      - name: Update Task Versions
        run: ./hack/openshift/update-openshift-tekton-task-versions.sh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1  # v8.1.1
        with:
          token: ${{ secrets.CHATOPS_TOKEN }}
          commit-message: "Update Tekton task versions"
          committer: tekton-bot <tekton-bot@users.noreply.github.com>
          author: Shubham Bhardwaj <shubbhar@redhat.com>
          signoff: true
          title: "Update Tekton task versions"
          body: |
            This PR automatically updates the task versions in the `fetch-tektoncd-catalog-tasks.sh` script.

            The versions are pulled from the latest available versions in the [tektoncd-catalog](https://github.com/openshift-pipelines/tektoncd-catalog) repository.
          branch: update-tekton-versions
          base: main
          labels: |
            automation
            release-note-none
          delete-branch: true
